export type ProjectBase = {
  title: string;
  year: string;
  category: string;
  liveUrl?: string;
  githubUrl?: string;
  accent: string;
  blurb: string;
  overview: string;
  problem: string;
  solution: string;
  techStack: string[];
  nextSlug: string;
  nextTitle: string;
};

export const PROJECTS: Record<string, ProjectBase> = {
  "recall-sap": {
    title: "Recall",
    year: "2025",
    category: "SAP / AI",
    githubUrl: "https://github.com/Abhijit1018",
    accent: "#7B9E87",
    blurb: "AI-driven SAP outreach system — identifies overdue customers and automates communication workflows via Twilio and email, integrated with SAP OData and CAP model.",
    overview: "Recall is an AI-powered SAP outreach system that automatically identifies overdue customers and drives communication workflows — built on SAP BTP using OData services, CAP model, and external AI tooling.",
    problem: "Enterprise teams managing accounts receivable manually spend hours identifying which customers are overdue and composing follow-up messages. The process is slow, inconsistent, and doesn't scale.",
    solution: "Recall connects to SAP OData services to pull financial data, applies AI-driven classification to prioritise overdue accounts, and automates outreach via Twilio SMS and email pipelines — cutting manual intervention to near zero.",
    techStack: ["SAP BTP", "ABAP CAP Model", "OData Services", "SAP Fiori", "AI Integration", "Twilio", "Email Automation"],
    nextSlug: "numen",
    nextTitle: "Numen",
  },
  "numen": {
    title: "Numen",
    year: "2026",
    category: "SAP / AI",
    accent: "#6B5B95",
    blurb: "Autonomous Enterprise Intelligence Platform for SAP — 17 multi-agent AI reasoning over a live business graph, from incident to root cause to rupee impact.",
    overview: "Numen is an autonomous Enterprise Intelligence Platform for SAP — a multi-agent AI system that watches enterprise events, finds root causes, translates them into business impact, and executes fixes with confidence-based approval. 17 agents across integration, finance, procurement, and governance, reasoning over a live business graph. Private repo — deep-dive available on request.",
    problem: "Enterprise incidents — a failed iFlow, an expiring OAuth token, a rejected bank file — get triaged manually, disconnected from their downstream business impact. Nobody can quickly answer \"why did cash flow drop this period?\" without days of cross-team detective work.",
    solution: "Numen's agents watch SAP BTP events, run root-cause analysis, and translate technical failures into rupee business impact — auto-executing high-confidence fixes and queuing the rest for approval. A graph reasoner traverses the business model (Cash to Receivables to unpaid invoices to the root iFlow bug) to explain incidents in business terms, and exposes the same intelligence to any AI agent via an MCP gateway.",
    techStack: ["Node.js", "TypeScript", "Multi-Agent AI", "SAP BTP (mocked)", "CAP CDS", "MCP", "Groq LLM", "Business Graph Reasoning", "React Dashboard"],
    nextSlug: "whitewire",
    nextTitle: "WhiteWire",
  },
  "whitewire": {
    title: "WhiteWire",
    year: "2026",
    category: "AI / Web",
    liveUrl: "https://whitewire.vercel.app",
    githubUrl: "https://github.com/Abhijit1018/whitewire",
    accent: "#7B93C4",
    blurb: "AI-native canvas for product teams — describe an idea, get a connected board with real schemas, APIs, ORM models, ER diagrams, and docs per node.",
    overview: "WhiteWire is an AI-native canvas for product teams — describe an idea and it builds a connected board of components, then generates real schemas, APIs, ORM models, ER diagrams, and docs per node. Bring-your-own-LLM: OpenAI-compatible endpoints, Anthropic, or Google, with keys encrypted at rest.",
    problem: "Product teams sketch ideas in tools that don't understand software — whiteboards and slide decks that need translating into schemas, APIs, and docs by hand every time. That translation step is slow and repeated for every project.",
    solution: "WhiteWire combines a React Flow canvas with a BYO-LLM pipeline: describe an idea and the AI lays out a connected board, then each node can generate its own schema, API contract, ORM model, ER diagram (rendered as real Mermaid), or docs, with staleness tracking when the source changes. An Architect Assist agent reviews the whole board and suggests what's missing.",
    techStack: ["Next.js 16", "React 19", "TypeScript", "Vercel AI SDK v7", "React Flow", "Supabase Auth", "Neon Postgres", "Drizzle ORM", "Tailwind CSS"],
    nextSlug: "arora-ai",
    nextTitle: "Arora AI",
  },
  "arora-ai": {
    title: "Arora AI",
    year: "2025",
    category: "AI / Python",
    githubUrl: "https://github.com/Abhijit1018/Arora-Ai",
    accent: "#7B9E87",
    blurb: "The master agent for your machine — an autonomous AI assistant built in Python with tool use, memory, and multi-step reasoning.",
    overview: "Arora AI is an autonomous agent built in Python — a master orchestrator that can use tools, maintain memory, and execute multi-step tasks on your machine.",
    problem: "Most AI assistants are stateless chat interfaces that forget context and can't take real actions. They're useful for generating text but fall short when you need something that actually works on your behalf.",
    solution: "Arora AI uses an agent loop architecture with tool use, persistent memory, and a planning layer that breaks complex goals into executable steps — closer to an autonomous assistant than a chatbot.",
    techStack: ["Python", "LLM APIs", "Tool Use / Function Calling", "Memory Management", "Async Python", "CLI"],
    nextSlug: "bharat-biz-agent",
    nextTitle: "Bharat Biz Agent",
  },
  "bharat-biz-agent": {
    title: "Bharat Biz Agent",
    year: "2025",
    category: "AI / Voice",
    githubUrl: "https://github.com/Abhijit1018/Bharat-Biz-Agent",
    accent: "#D4B896",
    blurb: "Voice + chat based business assistant for Hindi, English, and Hinglish speakers. Multi-lingual LLM orchestration for Indian SMEs.",
    overview: "A voice and chat based business assistant designed for Indian SMEs — supporting Hindi, English, and Hinglish in a single unified interface.",
    problem: "Language is a barrier for millions of small business owners in India. Most AI tools are English-only and miss the natural code-switching (Hinglish) that's ubiquitous in everyday business conversations.",
    solution: "A multi-lingual agent pipeline that handles voice input, language detection, LLM inference in the appropriate language, and voice output — all optimized for business use cases like inventory, billing queries, and customer management.",
    techStack: ["Python", "Speech-to-Text", "LLM Orchestration", "Hindi NLP", "Voice Interface", "FastAPI"],
    nextSlug: "shieldroute",
    nextTitle: "ShieldRoute",
  },
  "shieldroute": {
    title: "ShieldRoute",
    year: "2025",
    category: "TypeScript",
    githubUrl: "https://github.com/Abhijit1018/ShieldRoute",
    accent: "#C4847A",
    blurb: "A TypeScript-based secure routing framework. Declarative route protection with middleware composition.",
    overview: "A TypeScript-first secure routing framework that brings declarative route protection, role-based access control, and middleware composition to modern web applications.",
    problem: "Authentication and authorization logic gets scattered across codebases — sometimes in middleware, sometimes in components, sometimes nowhere. The result is security gaps that are hard to audit.",
    solution: "ShieldRoute centralizes access control into a declarative route configuration. Routes express their requirements; the framework enforces them. Middleware composes cleanly and the security model is auditable at a glance.",
    techStack: ["TypeScript", "Middleware Composition", "RBAC", "JWT", "Node.js"],
    nextSlug: "living-blossom",
    nextTitle: "Living Blossom",
  },
  "living-blossom": {
    title: "Living Blossom",
    year: "2025",
    category: "Web",
    githubUrl: "https://github.com/Abhijit1018/Living-Blossom",
    accent: "#A8C4B0",
    blurb: "A TypeScript web application — elegant UI with a focus on interaction design and component architecture.",
    overview: "A TypeScript web application with a focus on elegant UI design, fluid interactions, and a clean component architecture.",
    problem: "Building web interfaces that feel alive — not just functional — requires deliberate investment in motion, hierarchy, and interaction design at every layer.",
    solution: "Living Blossom explores these questions through a carefully designed component system with intentional animations, semantic color tokens, and interaction states that feel considered.",
    techStack: ["TypeScript", "React", "CSS Animations", "Component Architecture", "Design Tokens"],
    nextSlug: "nexus-os",
    nextTitle: "Nexus OS",
  },
  "nexus-os": {
    title: "Nexus OS",
    year: "2025",
    category: "TypeScript",
    githubUrl: "https://github.com/Abhijit1018/Nexus-OS",
    accent: "#9BB8A4",
    blurb: "An operating-system-inspired TypeScript project exploring windowed UI, file system abstractions, and process management in the browser.",
    overview: "An operating-system-inspired browser experience — windowed UI, simulated file system, and process management, all running in TypeScript.",
    problem: "OS-level UI concepts (windows, taskbars, file explorers) are rarely explored in browser contexts, yet they represent some of the most complex interaction patterns in software.",
    solution: "Nexus OS implements a windowed desktop environment entirely in the browser, with draggable windows, a virtual file system, and a process model — pushing TypeScript and DOM APIs to their limits.",
    techStack: ["TypeScript", "DOM APIs", "Virtual File System", "Window Management", "State Machine"],
    nextSlug: "legacy-lens",
    nextTitle: "LegacyLens",
  },
  "legacy-lens": {
    title: "LegacyLens",
    year: "2025",
    category: "Python",
    githubUrl: "https://github.com/Abhijit1018/LegacyLens",
    accent: "#BFA090",
    blurb: "The code legacy optimizer — analyzes Python codebases, identifies technical debt, and suggests refactoring paths using static analysis.",
    overview: "A code legacy optimizer — analyzes Python codebases for technical debt, identifies problematic patterns, and generates prioritized refactoring recommendations.",
    problem: "Every codebase accumulates legacy code — deprecated patterns, dead code, over-coupled modules — but there's no systematic way to understand the scope of the problem or where to start.",
    solution: "LegacyLens uses static analysis, dependency graphs, and heuristics to score code health and produce an actionable, prioritized roadmap for refactoring legacy systems.",
    techStack: ["Python", "AST Analysis", "Static Analysis", "Dependency Graphs", "CLI"],
    nextSlug: "code-legacy-frontend",
    nextTitle: "Code Legacy Frontend",
  },
  "code-legacy-frontend": {
    title: "Code Legacy Frontend",
    year: "2025",
    category: "Web",
    githubUrl: "https://github.com/Abhijit1018/Code-Legacy-frontend",
    accent: "#B0A8C4",
    blurb: "Frontend dashboard for the Code Legacy platform — visualizing codebase health metrics, technical debt scores, and refactoring recommendations.",
    overview: "The frontend dashboard for the Code Legacy platform — visualizing codebase health metrics, technical debt scores, and refactoring recommendations.",
    problem: "Static analysis data is only useful if it's presented clearly. Raw JSON from a Python analyzer doesn't help a team make decisions about where to invest refactoring effort.",
    solution: "An interactive dashboard that transforms analyzer output into visual health scores, dependency graphs, and prioritized action lists — making complex codebase data immediately understandable.",
    techStack: ["Python", "JavaScript", "Data Visualization", "Dashboard UI", "REST API"],
    nextSlug: "e-flower",
    nextTitle: "E-Flower",
  },
  "e-flower": {
    title: "E-Flower",
    year: "2025",
    category: "Web",
    githubUrl: "https://github.com/Abhijit1018/E-flower",
    accent: "#C4A8B0",
    blurb: "Full-stack e-commerce application for a floral business, with product catalog, cart, and order management.",
    overview: "A full-stack e-commerce application for a floral business — product catalog, cart management, order processing, and a backend API.",
    problem: "Local florist businesses need affordable, custom online storefronts that match their brand without the overhead of Shopify or WooCommerce.",
    solution: "A lightweight full-stack e-commerce solution with a JavaScript frontend, backend API, and a clean product catalog UX designed for visual products like flowers.",
    techStack: ["JavaScript", "Node.js", "REST API", "E-commerce UX", "Full-Stack"],
    nextSlug: "mindinspo",
    nextTitle: "MindInspo",
  },
  "mindinspo": {
    title: "MindInspo",
    year: "2026",
    category: "AI / Automation",
    githubUrl: "https://github.com/Abhijit1018/MINDINSPO",
    accent: "#C4847A",
    blurb: "AI-powered idea incubator — submit a concept, get back a structured technical catalog: stack, trade-offs, comparables, and an architecture diagram.",
    overview: "MindInspo is an AI-powered idea incubator — submit a raw concept and it returns a structured technical catalog: recommended stack, pros and cons, comparable tools, and a system architecture diagram, generated through an automated AI workflow.",
    problem: "Turning a raw idea into a scoped technical plan — stack choices, architecture, comparable tools — usually takes hours of manual research before a single line of code gets written.",
    solution: "A Flask backend and React + Vite dashboard sit on top of an n8n workflow that pipes the idea through an LLM (Groq/OpenAI), returning a structured catalog — summary, stack, trade-offs, similar tools, and a Mermaid architecture diagram — stored and browsable per idea.",
    techStack: ["Python", "Flask", "React", "Vite", "n8n", "SQLite", "SQLAlchemy", "LLM (Groq/OpenAI)", "Tailwind CSS"],
    nextSlug: "redhope",
    nextTitle: "REDHOPE",
  },
  "redhope": {
    title: "REDHOPE",
    year: "2025",
    category: "Django",
    githubUrl: "https://github.com/Abhijit1018",
    accent: "#B07070",
    blurb: "Blood and organ delivery logistics platform — inventory management, delivery tracking, and real-time coordination between hospitals and vendors.",
    overview: "REDHOPE is a blood and organ delivery logistics platform — managing inventory, tracking deliveries, and coordinating real-time communication between hospitals and vendors.",
    problem: "Blood and organ logistics require near-zero error tolerance and real-time coordination between multiple parties. Most existing systems are fragmented, with no unified view of inventory, requests, and delivery status.",
    solution: "A Django-powered platform with inventory management, delivery tracking, request workflows, and authentication — structured for real-time coordination between hospitals and vendors with analytics dashboards.",
    techStack: ["Python", "Django", "REST APIs", "MySQL", "Authentication", "Analytics Dashboard"],
    nextSlug: "sap-fiori-sales",
    nextTitle: "SAP Fiori Sales Order App",
  },
  "sap-fiori-sales": {
    title: "SAP Fiori Sales Order App",
    year: "2025",
    category: "SAP",
    githubUrl: "https://github.com/Abhijit1018",
    accent: "#6090A0",
    blurb: "Fiori UI5 application for sales order processing — built with SAPUI5, ABAP backend logic, and OData services for real-time synchronization.",
    overview: "A Fiori UI5 application for end-to-end sales order processing — built with SAPUI5 on the frontend, ABAP backend business logic, and OData services for real-time synchronization.",
    problem: "SAP's default transaction interfaces for sales order management are dense and require significant training. Modern enterprise users expect familiar web-app patterns without sacrificing SAP's transactional integrity.",
    solution: "A Fiori-native application that surfaces the core sales order workflow in a clean SAPUI5 interface, backed by ABAP-driven business logic and OData services ensuring live data sync with the SAP backend.",
    techStack: ["SAPUI5", "SAP Fiori", "ABAP", "OData Services", "SAP BTP", "BAS (Business Application Studio)"],
    nextSlug: "recall-sap",
    nextTitle: "Recall",
  },
};

export const PROJECT_SLUGS = Object.keys(PROJECTS);
